const data = {
    "442259": {
        "ID": "442259",
        "Orden": 1,
        "Apellido": "Absalón Wong",
        "Nombre": "Gloria Oliva",
        "Correo": "gloria.absalon@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "441829": {
        "ID": "441829",
        "Orden": 2,
        "Apellido": "Acuña Molina",
        "Nombre": "Mara Patricia",
        "Correo": "00441829@anahuac.mx",
        "Promedio": "9.79",
        "NRC": "51217",
        "Sede": "Residencia Luna Nueva (Residencia para adultos mayores)",
        "Estatus": "Asignado"
    },
    "366037": {
        "ID": "366037",
        "Orden": 3,
        "Apellido": "Aguirre Fuentes",
        "Nombre": "Karime",
        "Correo": "00366037@anahuac.mx",
        "Promedio": "9.8",
        "NRC": "51217",
        "Sede": "DACODES",
        "Estatus": "Asignado"
    },
    "421721": {
        "ID": "421721",
        "Orden": 4,
        "Apellido": "Alducin Rosales",
        "Nombre": "Elizabeth",
        "Correo": "00421721@anahuac.mx",
        "Promedio": "8.5",
        "NRC": "51217",
        "Sede": "C&C Empresarial",
        "Estatus": "Asignado"
    },
    "437887": {
        "ID": "437887",
        "Orden": 5,
        "Apellido": "Álvarez Mikel",
        "Nombre": "Ximena",
        "Correo": "00437887@anahuac.mx",
        "Promedio": "8.61",
        "NRC": "51269",
        "Sede": "Loyola Comunidad Educativa",
        "Estatus": "Asignado"
    },
    "444541": {
        "ID": "444541",
        "Orden": 6,
        "Apellido": "Asencio Villamil",
        "Nombre": "Elena",
        "Correo": "elena.asencio@anahuac.mx",
        "Promedio": "9.04",
        "NRC": "51217",
        "Sede": "Arte y Cultura UAM",
        "Estatus": "Asignado"
    },
    "462432": {
        "ID": "462432",
        "Orden": 7,
        "Apellido": "Azueta Heredia",
        "Nombre": "Faith Kristen",
        "Correo": "faith.azueta@anahuac.mx",
        "Promedio": "8.73",
        "NRC": "51269",
        "Sede": "Centros de Integración Juvenil A.C. (CIJ)",
        "Estatus": "Asignado"
    },
    "440090": {
        "ID": "440090",
        "Orden": 8,
        "Apellido": "Bacelis Espinoza",
        "Nombre": "Sofía Marisol",
        "Correo": "sofia.bacelis@anahuac.mx",
        "Promedio": "9.01",
        "NRC": "51217",
        "Sede": "Arte y Cultura UAM",
        "Estatus": "Asignado"
    },
    "418967": {
        "ID": "418967",
        "Orden": 9,
        "Apellido": "Baeza Barceló",
        "Nombre": "Daniela",
        "Correo": "00418967@anahuac.mx",
        "Promedio": "9.07",
        "NRC": "51217",
        "Sede": "Arte y Cultura UAM",
        "Estatus": "Asignado"
    },
    "438851": {
        "ID": "438851",
        "Orden": 10,
        "Apellido": "Beltrán Castillo",
        "Nombre": "Karla Melanie",
        "Correo": "karla.beltran@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "446089": {
        "ID": "446089",
        "Orden": 11,
        "Apellido": "Bonifaz Gamboa",
        "Nombre": "Karla Joanna",
        "Correo": "karla.bonifaz@anahuac.mx",
        "Promedio": "9.33",
        "NRC": "51217",
        "Sede": "Tiny Humans",
        "Estatus": "Asignado"
    },
    "465833": {
        "ID": "465833",
        "Orden": 12,
        "Apellido": "Cabrera Ramírez",
        "Nombre": "Emily",
        "Correo": "emily.cabrera@anahuac.mx",
        "Promedio": "9.05",
        "NRC": "51269",
        "Sede": "AYUDA (Asociación Yucateca de Lucha contra el Autismo)",
        "Estatus": "Asignado"
    },
    "470411": {
        "ID": "470411",
        "Orden": 13,
        "Apellido": "Camara Marrufo",
        "Nombre": "María Eugenia",
        "Correo": "maria_camara@anahuac.mx",
        "Promedio": "8.65",
        "NRC": "51269",
        "Sede": "Prepa Anáhuac Mérida",
        "Estatus": "Asignado"
    },
    "444797": {
        "ID": "444797",
        "Orden": 14,
        "Apellido": "Campos Loría",
        "Nombre": "Ana Paulina",
        "Correo": "ana_campos@anahuac.mx",
        "Promedio": "8.27",
        "NRC": "51269",
        "Sede": "Madison International School",
        "Estatus": "Asignado"
    },
    "439463": {
        "ID": "439463",
        "Orden": 15,
        "Apellido": "Cantón Paredes",
        "Nombre": "Gissel De los Ángeles",
        "Correo": "gissel_canton@anahuac.mx",
        "Promedio": "8.31",
        "NRC": "51269",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "En revisión"
    },
    "446565": {
        "ID": "446565",
        "Orden": 16,
        "Apellido": "Castillejos Cabrera",
        "Nombre": "Ana Lucía",
        "Correo": "ana.castillejos@anahuac.mx",
        "Promedio": "8.31",
        "NRC": "51269",
        "Sede": "Sedes Tipo C",
        "Estatus": "En revisión"
    },
    "449543": {
        "ID": "449543",
        "Orden": 17,
        "Apellido": "Castillo Mancera",
        "Nombre": "Jeanet",
        "Correo": "00449543@anahuac.mx",
        "Promedio": "9.35",
        "NRC": "51217",
        "Sede": "Mano amiga",
        "Estatus": "Asignado"
    },
    "374225": {
        "ID": "374225",
        "Orden": 18,
        "Apellido": "Chan Estrella",
        "Nombre": "José Ángel",
        "Correo": "00374225@anahuac.mx",
        "Promedio": "7.69",
        "NRC": "51269",
        "Sede": "Residencia Luna Nueva (Residencia para adultos mayores)",
        "Estatus": "Asignado"
    },
    "460924": {
        "ID": "460924",
        "Orden": 19,
        "Apellido": "Chang Gómez",
        "Nombre": "Eva Alejandra",
        "Correo": "eva.chang@anahuac.mx",
        "Promedio": "9.11",
        "NRC": "51217",
        "Sede": "CETIS 112",
        "Estatus": "Asignado"
    },
    "452490": {
        "ID": "452490",
        "Orden": 20,
        "Apellido": "Chávez Recinos",
        "Nombre": "Daniela Elizabeth",
        "Correo": "daniela.chavez@anahuac.mx",
        "Promedio": "9.15",
        "NRC": "51217",
        "Sede": "Fundación Teletón",
        "Estatus": "En revisión"
    },
    "440342": {
        "ID": "440342",
        "Orden": 21,
        "Apellido": "Chong López",
        "Nombre": "Liliana",
        "Correo": "liliana.chong@anahuac.mx",
        "Promedio": "9.12",
        "NRC": "51269",
        "Sede": "Arte y Cultura UAM",
        "Estatus": "Asignado"
    },
    "440633": {
        "ID": "440633",
        "Orden": 22,
        "Apellido": "Duarte Axle",
        "Nombre": "Ana Valenka",
        "Correo": "valenka.duarte@anahuac.mx",
        "Promedio": "9.45",
        "NRC": "51217",
        "Sede": "Arte y Cultura UAM",
        "Estatus": "Asignado"
    },
    "448831": {
        "ID": "448831",
        "Orden": 23,
        "Apellido": "Echeverría Castro",
        "Nombre": "Daniela Noemí",
        "Correo": "daniela.echeverria@anahuac.mx",
        "Promedio": "8.22",
        "NRC": "51217",
        "Sede": "Fundación Palace IAP",
        "Estatus": "Asignado"
    },
    "351743": {
        "ID": "351743",
        "Orden": 24,
        "Apellido": "Estrada Martínez",
        "Nombre": "Karime Alexa",
        "Correo": "00351743@anahuac.mx",
        "Promedio": "8.75",
        "NRC": "51217",
        "Sede": "AYUDA (Asociación Yucateca de Lucha contra el Autismo)",
        "Estatus": "Asignado"
    },
    "447148": {
        "ID": "447148",
        "Orden": 25,
        "Apellido": "Estrada Vaquerizo",
        "Nombre": "Karen",
        "Correo": "kestrada@anahuac.mx",
        "Promedio": "9.2",
        "NRC": "51269",
        "Sede": "Manufacturas Salmon SA de CB",
        "Estatus": "En revisión"
    },
    "449749": {
        "ID": "449749",
        "Orden": 26,
        "Apellido": "Gómez Lara",
        "Nombre": "Jimena Guadalupe",
        "Correo": "jimena.gmez@anahuac.mx",
        "Promedio": "9.59",
        "NRC": "51217",
        "Sede": "Restaurant Bar y Hotel el Faisán Y el Venado",
        "Estatus": "En revisión"
    },
    "459556": {
        "ID": "459556",
        "Orden": 27,
        "Apellido": "González Otto",
        "Nombre": "Arlette",
        "Correo": "arlette.otto@anahuac.mx",
        "Promedio": "8.9",
        "NRC": "51269",
        "Sede": "Manufacturas Salmón, S.A  DE C.V.",
        "Estatus": "En revisión"
    },
    "355477": {
        "ID": "355477",
        "Orden": 28,
        "Apellido": "González Ramírez",
        "Nombre": "Aitana Sofía",
        "Correo": "00355477@anahuac.mx",
        "Promedio": "8.93",
        "NRC": "51217",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "Asignado"
    },
    "436576": {
        "ID": "436576",
        "Orden": 29,
        "Apellido": "Gudiño Ramos",
        "Nombre": "Giovanni Samuel",
        "Correo": "giovanni_gudino@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51217",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "438149": {
        "ID": "438149",
        "Orden": 30,
        "Apellido": "Guerrero Oropeza",
        "Nombre": "Emiliano",
        "Correo": "emiliano.guerrero@anahuac.mx",
        "Promedio": "9.21",
        "NRC": "51269",
        "Sede": "Loyola Comunidad Educativa",
        "Estatus": "Asignado"
    },
    "418576": {
        "ID": "418576",
        "Orden": 31,
        "Apellido": "Hernandez",
        "Nombre": "Sofia",
        "Correo": "00418576@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51217",
        "Sede": "JAKO",
        "Estatus": "En revisión"
    },
    "455332": {
        "ID": "455332",
        "Orden": 32,
        "Apellido": "Hernández Celada",
        "Nombre": "Aleck Fernando",
        "Correo": "00455332@anahuac.mx",
        "Promedio": "8.2",
        "NRC": "51217",
        "Sede": "Centro Especializado en Diabetes",
        "Estatus": "En revisión"
    },
    "429013": {
        "ID": "429013",
        "Orden": 33,
        "Apellido": "Hernández Vergara",
        "Nombre": "Alejandra",
        "Correo": "avergara@anahuac.mx",
        "Promedio": "8.16",
        "NRC": "51217",
        "Sede": "Centros de Integración Juvenil A.C. (CIJ)",
        "Estatus": "Asignado"
    },
    "398561": {
        "ID": "398561",
        "Orden": 34,
        "Apellido": "Herrera Pérez",
        "Nombre": "María Yolanda",
        "Correo": "00398561@anahuac.mx",
        "Promedio": "9.69",
        "NRC": "51217",
        "Sede": "DACODES",
        "Estatus": "Asignado"
    },
    "407313": {
        "ID": "407313",
        "Orden": 35,
        "Apellido": "Homs Díaz Muñoz",
        "Nombre": "Mariana",
        "Correo": "00407313@anahuac.mx",
        "Promedio": "9.31",
        "NRC": "51217",
        "Sede": "Tiny Humans",
        "Estatus": "Asignado"
    },
    "440132": {
        "ID": "440132",
        "Orden": 36,
        "Apellido": "Jaramillo Romo",
        "Nombre": "Sofía",
        "Correo": "sofia.jaramillo@anahuac.mx",
        "Promedio": "8.75",
        "NRC": "51269",
        "Sede": "Loyola Comunidad Educativa",
        "Estatus": "Asignado"
    },
    "386264": {
        "ID": "386264",
        "Orden": 37,
        "Apellido": "Jimenez Ayala",
        "Nombre": "Sary",
        "Correo": "00386264@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "474689": {
        "ID": "474689",
        "Orden": 38,
        "Apellido": "López Colomé",
        "Nombre": "Ivana",
        "Correo": "ivana.lopez@anahuac.mx",
        "Promedio": "9.2",
        "NRC": "51217",
        "Sede": "Consultorio del PsicólogoSarkis Kuri Auais",
        "Estatus": "En revisión"
    },
    "440472": {
        "ID": "440472",
        "Orden": 39,
        "Apellido": "Mar García",
        "Nombre": "Carla Cristel",
        "Correo": "carla.mar@anahuac.mx",
        "Promedio": "8.3",
        "NRC": "51217",
        "Sede": "La Mueblería V",
        "Estatus": "En revisión"
    },
    "380938": {
        "ID": "380938",
        "Orden": 40,
        "Apellido": "Martinez Hidalgo",
        "Nombre": "Ximena",
        "Correo": "00380938@anahuac.mx",
        "Promedio": "9.04",
        "NRC": "51269",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "Asignado"
    },
    "440129": {
        "ID": "440129",
        "Orden": 41,
        "Apellido": "Marzuca Agramont",
        "Nombre": "Tany Patricia",
        "Correo": "tany.marzuca@anahuac.mx",
        "Promedio": "9.17",
        "NRC": "51217",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "En revisión"
    },
    "465081": {
        "ID": "465081",
        "Orden": 42,
        "Apellido": "Medina Ruz",
        "Nombre": "Ana Paula",
        "Correo": "ana.medina23@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "469836": {
        "ID": "469836",
        "Orden": 43,
        "Apellido": "Molina Arenivar",
        "Nombre": "Daniela Alexandra",
        "Correo": "daniela.molina28@anahuac.mx",
        "Promedio": "9.6",
        "NRC": "51269",
        "Sede": "AYUDA (Asociación Yucateca de Lucha contra el Autismo)",
        "Estatus": "Asignado"
    },
    "413414": {
        "ID": "413414",
        "Orden": 44,
        "Apellido": "Montalvo Bermejo",
        "Nombre": "Dulce",
        "Correo": "00413414@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "441831": {
        "ID": "441831",
        "Orden": 45,
        "Apellido": "Nucamendi Martínez",
        "Nombre": "Andrea Lisseth",
        "Correo": "lisseth.nucamendi@anahuac.mx",
        "Promedio": "9.02",
        "NRC": "51217",
        "Sede": "Tiny Humans",
        "Estatus": "Asignado"
    },
    "378853": {
        "ID": "378853",
        "Orden": 46,
        "Apellido": "Ortiz Aquino",
        "Nombre": "María Paola",
        "Correo": "00378853@anahuac.mx",
        "Promedio": "8.79",
        "NRC": "51269",
        "Sede": "Residencia Luna Nueva (Residencia para adultos mayores)",
        "Estatus": "Asignado"
    },
    "419110": {
        "ID": "419110",
        "Orden": 47,
        "Apellido": "Osorio Miranda",
        "Nombre": "Sebastián",
        "Correo": "00419110@anahuac.mx",
        "Promedio": "8.52",
        "NRC": "51269",
        "Sede": "AYUDA (Asociación Yucateca de Lucha contra el Autismo)",
        "Estatus": "Asignado"
    },
    "369565": {
        "ID": "369565",
        "Orden": 48,
        "Apellido": "Padilla Castillejos",
        "Nombre": "Sophia Valeria",
        "Correo": "00369565@anahuac.mx",
        "Promedio": "8.88",
        "NRC": "51269",
        "Sede": "Polpusa",
        "Estatus": "Asignado"
    },
    "479190": {
        "ID": "479190",
        "Orden": 49,
        "Apellido": "Pérez Arciniega",
        "Nombre": "Vicente",
        "Correo": "vicente.perez@anahuac.mx",
        "Promedio": "8.91",
        "NRC": "51269",
        "Sede": "Mano amiga",
        "Estatus": "Asignado"
    },
    "369928": {
        "ID": "369928",
        "Orden": 50,
        "Apellido": "Pérez Ávila",
        "Nombre": "Alma Alejandra",
        "Correo": "00369928@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "Instituto México para la Educación AC",
        "Estatus": "En revisión"
    },
    "454268": {
        "ID": "454268",
        "Orden": 51,
        "Apellido": "Pérez Campos",
        "Nombre": "Genaro David",
        "Correo": "genaro.campos@anahuac.mx",
        "Promedio": "9.14",
        "NRC": "51217",
        "Sede": "Fortunia México",
        "Estatus": "En revisión"
    },
    "455256": {
        "ID": "455256",
        "Orden": 52,
        "Apellido": "Pérez Tapia",
        "Nombre": "Regina Tiare",
        "Correo": "00455256@anahuac.mx",
        "Promedio": "8.07",
        "NRC": "51269",
        "Sede": "Residencia Luna Nueva (Residencia para adultos mayores)",
        "Estatus": "Asignado"
    },
    "464118": {
        "ID": "464118",
        "Orden": 53,
        "Apellido": "Pichardo Urrutia",
        "Nombre": "Paulina",
        "Correo": "paulina.pichardo@anahuac.mx",
        "Promedio": "9.37",
        "NRC": "51269",
        "Sede": "AYUDA (Asociación Yucateca de Lucha contra el Autismo)",
        "Estatus": "Asignado"
    },
    "447477": {
        "ID": "447477",
        "Orden": 54,
        "Apellido": "Prado Delgado",
        "Nombre": "Bernardo Rafael",
        "Correo": "rprado@anahuac.mx",
        "Promedio": "8.97",
        "NRC": "51269",
        "Sede": "GRUPO GOMEX (AVIS)",
        "Estatus": "En revisión"
    },
    "455652": {
        "ID": "455652",
        "Orden": 55,
        "Apellido": "Ramírez Castellanos",
        "Nombre": "Sofía",
        "Correo": "sofia_ramirez@anahuac.mx",
        "Promedio": "8.15",
        "NRC": "51269",
        "Sede": "Amanecer Nuevamente (Centro de Rehabilitación y Tratamiento para Mujeres)",
        "Estatus": "Asignado"
    },
    "447999": {
        "ID": "447999",
        "Orden": 56,
        "Apellido": "Robles Graham",
        "Nombre": "Juan José",
        "Correo": "juan.graham@anahuac.mx",
        "Promedio": "8.08",
        "NRC": "51269",
        "Sede": "Residencia Luna Nueva (Residencia para adultos mayores)",
        "Estatus": "Asignado"
    },
    "442861": {
        "ID": "442861",
        "Orden": 57,
        "Apellido": "Rodríguez Orellana",
        "Nombre": "Emilio Alejandro",
        "Correo": "emilio_rodriguez@anahuac.mx",
        "Promedio": "8.01",
        "NRC": "51269",
        "Sede": "Loyola Comunidad Educativa",
        "Estatus": "Asignado"
    },
    "445573": {
        "ID": "445573",
        "Orden": 58,
        "Apellido": "Rojas Noriega",
        "Nombre": "Sebastián",
        "Correo": "sebastian.rojas@anahuac.mx",
        "Promedio": "8.01",
        "NRC": "51217",
        "Sede": "Centro Especializado en Diabetes",
        "Estatus": "En revisión"
    },
    "373362": {
        "ID": "373362",
        "Orden": 59,
        "Apellido": "Rosado Dimayuga",
        "Nombre": "Ian Martin",
        "Correo": "00373362@anahuac.mx",
        "Promedio": "8.69",
        "NRC": "51217",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "Asignado"
    },
    "458664": {
        "ID": "458664",
        "Orden": 60,
        "Apellido": "Rosado Rivas",
        "Nombre": "Juan Pablo",
        "Correo": "jrosado@anahuac.mx",
        "Promedio": "9.23",
        "NRC": "51269",
        "Sede": "Mano amiga",
        "Estatus": "Asignado"
    },
    "389205": {
        "ID": "389205",
        "Orden": 61,
        "Apellido": "Sosa Sanchez",
        "Nombre": "Paulina",
        "Correo": "00389205@anahuac.mx",
        "Promedio": "8.87",
        "NRC": "51217",
        "Sede": "Centros de Integración Juvenil A.C. (CIJ)",
        "Estatus": "Asignado"
    },
    "453725": {
        "ID": "453725",
        "Orden": 62,
        "Apellido": "Souto De Onazar",
        "Nombre": "Ráina",
        "Correo": "raina.souto19@anahuac.mx",
        "Promedio": "8.53",
        "NRC": "51269",
        "Sede": "Rancho de Picanha",
        "Estatus": "En revisión"
    },
    "452704": {
        "ID": "452704",
        "Orden": 63,
        "Apellido": "Tabares López",
        "Nombre": "Kelly María",
        "Correo": "kelly.tabares@anahuac.mx",
        "Promedio": "8.24",
        "NRC": "51269",
        "Sede": "Fiscalía",
        "Estatus": "En revisión"
    },
    "449529": {
        "ID": "449529",
        "Orden": 64,
        "Apellido": "Toledo Lugo",
        "Nombre": "Christian María",
        "Correo": "mtoledo@anahuac.mx",
        "Promedio": "9.31",
        "NRC": "51269",
        "Sede": "Centros de Integración Juvenil A.C. (CIJ)",
        "Estatus": "Asignado"
    },
    "470002": {
        "ID": "470002",
        "Orden": 65,
        "Apellido": "Torres Espindola",
        "Nombre": "Adelina",
        "Correo": "adelina.torres@anahuac.mx",
        "Promedio": "8.91",
        "NRC": "51269",
        "Sede": "Centros de Integración Juvenil A.C. (CIJ)",
        "Estatus": "Asignado"
    },
    "440243": {
        "ID": "440243",
        "Orden": 66,
        "Apellido": "Vazquez Caballero",
        "Nombre": "Melissa",
        "Correo": "melissa.vazquez@anahuac.mx",
        "Promedio": "8.78",
        "NRC": "51217",
        "Sede": "Tiny Humans",
        "Estatus": "Asignado"
    },
    "412734": {
        "ID": "412734",
        "Orden": 67,
        "Apellido": "Vazquez Castillo",
        "Nombre": "Emiliano",
        "Correo": "00412734@anahuac.mx",
        "Promedio": "8.82",
        "NRC": "51217",
        "Sede": "Pastoral del Amor A.C.",
        "Estatus": "Asignado"
    },
    "444121": {
        "ID": "444121",
        "Orden": 68,
        "Apellido": "Vázquez Escobar",
        "Nombre": "Gabriela",
        "Correo": "gabriela_vazquez@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "458841": {
        "ID": "458841",
        "Orden": 69,
        "Apellido": "Villegas Jaimes",
        "Nombre": "Juan David",
        "Correo": "dvillegas@anahuac.mx",
        "Promedio": "Sin Dato",
        "NRC": "51269",
        "Sede": "No brindo sede",
        "Estatus": "No brindo sede"
    },
    "479817": {
        "ID": "479817",
        "Orden": 70,
        "Apellido": "Villorin Galaviz",
        "Nombre": "Edgar Arturo",
        "Correo": "00479817@anahuac.mx",
        "Promedio": "8.41",
        "NRC": "51217",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "En revisión"
    },
    "463805": {
        "ID": "463805",
        "Orden": 71,
        "Apellido": "Vivar Pacheco",
        "Nombre": "Angel",
        "Correo": "angel_vivar@anahuac.mx",
        "Promedio": "8.86",
        "NRC": "51217",
        "Sede": "Arrigunaga y Cano Consultores",
        "Estatus": "Asignado"
    },
    "470867": {
        "ID": "470867",
        "Orden": 72,
        "Apellido": "Xacur Quintal",
        "Nombre": "Valentina",
        "Correo": "valentina.xacur@anahuac.mx",
        "Promedio": "8.49",
        "NRC": "51269",
        "Sede": "Sedes Tipo C",
        "Estatus": "En revisión"
    }
};



